### ISSUE TITLE
ex-02: rename files

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#21]
Die Dateien sollten einheitlich benannt werde.

**Comment by hmmst** [comment]
Da bisher die meisten files Aufgabe<Nummer>.png bzw Aufgabe<Nummer>.xml benannt worden sind, schlage ich vor dieses Format zu übernehmen.

**Comment by hmmst** [comment]
naja jetzt sieht es eher so aus als wäre die ex[Nummer].png - Konvention beliebter..^^

was meint ihr? @bastidest2 @akramer123

**Comment by bastidest** [comment]
bin immer davon ausgegangen dass es ex[Nummer].png ist. Ist kuerzer^^

**Comment by hmmst** [comment]
:+1: da bin ich deiner Meinung.. :wink:
