### ISSUE TITLE
Willkommen

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#26]
Als Nutzer will ich nach Öffnen der Applikation über den Befehl ("Alexa, öffne Hypershop") von ihr begrüßt werden und gefragt werden, was ich als nächstes tun will.

Akzeptanz:

- [x] Begrüßung nach dem Öffnen der Applikation
- [x] Frage der Applikation, was als nächstes getan werden soll

**Comment by akramer123** [comment]
Meiner Meinung nach ist das hier bereits abgeschlossen?

**Comment by hmmst** [comment]
ich denke auch.. hat @bastidest2 anscheinend beim colorpicker kopieren schon angepasst..

**Comment by bastidest** [comment]
> Frage der Applikation, was als nächstes getan werden soll

Das gibt es aber noch nicht

**Comment by akramer123** [comment]
Das hab ich gerade nachgelesen.
Das hast du bereits als Reprompt angelegt.
Reprompts werden bei offenem Mikro für 8 Sekunden ausgegeben.

**Comment by bastidest2** [comment]
Ok, dann kann es geschlossen werden
