### ISSUE TITLE
Beenden

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#27]
Als Nutzer will ich die Applikation wieder verlassen können.

Akzeptanzkriterien:
- [x] Die Applikation kann mit einem Befehl beendet werden
- [x] Die Applikation verabschiedet sich mit den Worten "Bis bald."
- [x] Daten zu Rezepten und Einkaufsliste sind immer noch vorhanden

**Comment by hmmst** [comment]
@bastidest2 @akramer123 

Werden die Akzeptanzkriterien nicht mit #58 / #65 erfüllt?

**Comment by bastidest2** [comment]
Genau, meines erachtens erfüllt

**Comment by hmmst** [comment]
wurde irgendwie nicht automatisch durch #65 gecloset...
