### ISSUE TITLE
Zutat zur Einkaufsliste hinzufügen

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#32]
Als Nutzer will ich Zutaten zu der Einkaufsliste hinzufügen.

Akzeptanzkriterien:
- Der Nutzer kann eine Zutat mit Namen, Menge und Einheit hinzufügen
- Bei gleicher Zutat und Einheit wird zunächst eine Fehlermeldung ausgegeben

**Comment by akramer123** [comment]
Sollen wir das Zutatmergen momentan noch raus lassen und später als Feature hinzufügen?
In dem Fall muss bei den Akzeptanzkriterien stehen, dass die selbe Zutat mehrfach hinzugefügt werden kann mit unterschiedlichen Einheiten.

**Comment by hmmst** [comment]
ich denke, dass man ein simples mergen relativ schnell hinzufügen kann, also wenn Einheit und Zutat gleich sind, dann einfach Addieren... aber auch das sollten wir wahrscheinlich als eigene story schreiben..

**Comment by akramer123** [comment]
@hmmst @bastidest2 
Um Units abspeichern zu können müsste diese Unit-Map vorhanden sein.
Soll das in diesem Issue schon umgesetzt werden?

**Comment by hmmst** [comment]
welche Unit-Map meinst du? zur Einheitenumrechnung? die würde ich ersteinmal weglassen..

**Comment by akramer123** [comment]
Da wir die Units ja nicht in der Datenbank speichern benötigen wir eine Map mit allen Units die wir verarbeiten wollen.

**Comment by bastidest2** [comment]
Das Issue sagt nur dass es gespeichert werden soll, ich würde für diesen Sprint die Einheiten noch nicht wirklich interpretieren oder so, sondern einfach als String speichern

**Comment by hmmst** [comment]
@bastidest2 das würde ich genauso machen..:+1:

**Comment by akramer123** [comment]
Dann ändern wir das Datenmodell vorerst ab, sodass IngredientAmount nicht Unit sondern String als Typ für unit hat?

**Comment by bastidest2** [comment]
Ich würde das eher so anpassen dass alles in den Namen des IngredientAmount kommt. `name = "ein Kilo Kartoffeln". Dann kann man mit `equals` erkennen ob die selbe Zutat schon drinnen ist.

**Comment by akramer123** [comment]
Da momentan noch keine Map mit verfügbaren Units gibt, wird ein neues Unit Objekt mit übergebenem string als name erstellt. 
Dadurch ist folgende Anforderung momentan noch nicht umsetzbar:
Bei gleicher Zutat und Einheit wird zunächst eine Fehlermeldung ausgegeben
