### ISSUE TITLE
Einheiten - Umrechnung

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#36]
Als Nutzer will ich, dass die Mengenangaben von Einträgen und Zutaten in Einheiten gespeichert werden, die umgewandelt werden. Bsp.: 1 Tasse ~ 50g

Akzeptanzkriterien:
- Der Nutzer kann nach einer Umrechnung fragen.
- Die Einheiten der Zutaten werden automatisch umgewandelt.
- Selbiges gilt auch für die Zutaten der Rezepte

**Comment by bastidest2** [comment]
Das denke ich fällt aus dem Rahmen dieses Sprints. Fügt sich nicht so gut in das Gesamtkonzept ein, bin für Schließung des Issues

**Comment by hmmst** [comment]
sehe ich genau so, vor allem, weil es eigentlich unmöglich ist, auf eine eindeutige SI-Einheit zu mappen..

**Comment by bastidest2** [comment]
Überschreitet wie besprochen den Umfang, wird geschlossen.
