### ISSUE TITLE
Summieren der Zutatenmengen

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#37]
Als Nutzer will ich, dass mehrere Einträge und Zutaten automatisch zusammengerechnet werden, um bei der Ausgabe jedes Produkt nur einmal vorkommt.

Akzeptanzkriterien:
- Alle Zutaten mit gleichem Namen und gleicher Einheit werden zusammengefasst
- Dabei wird die Menge addiert.
- Selbiges gilt auch für die Zutaten eines Rezeptes

**Comment by akramer123** [comment]
Sollte das Feature hinzugefügt werden, dass bei einer bestimmten Menge bei bestimmten Einheiten automatisch auf die nächsthöhere gewechselt wird?
Das könnte über die UnitConversion gelöst werden.
zB.: Menge 2000 Unit: g -> 2 kg

**Comment by hmmst** [comment]
klingt gut.. nehme ich als neue Story auf..
