### ISSUE TITLE
add description for use cases

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#42]
Erstellen Sie ein Anwendungsfalldiagramm für das Praktikumsprojekt und beschreiben Sie alle Anwendungsfälle gemäß der in der Vorlesung besprochenen Anwendungsfallbeschreibung (siehe Oestereich, Analyse und Design mit UML 2.1/3/5, S. 119 (8. Auflage), S. 126 (10. Auflage), S. 75 (11.Auflage)). Anwendungsfalldiagramm und Anwendungsfallbeschreibungen stellen Sie in das Wiki Ihres Github Repositories. Hier sind nur Systemanwendungsfälle gefordert.

-> Tabellarische Anwendungsfallbeschreibung

**Comment by bastidest** [comment]
@hmmst @akramer123 
https://github.com/sweIhm-ws2018-19/skillproject-fr-11/wiki/Use-Cases
Bitte überprüfen

**Comment by hmmst** [comment]
Irgendwas stimmt mit den Anführungszeichen noch nicht, kann das sein?^^

**Comment by hmmst** [comment]
Überschriften wären noch ganz schön.. damit es ein bisschen übersichtlicher wird..

**Comment by akramer123** [comment]
Bei Use case: Rezept löschen
Muss hier das Rezept noch bei Ablauf eventuell aus dem Warenkorb gelöscht werden?

Zutat zu Einkaufsliste hinzufügen:
- Zusammenfügen von Zutaten wenn schon vorhanden

Ansonsten könnte man bei ein paar Use Cases das intelligente Einheitenumrechnen einfügen, aber ist das bei uns jetzt optional?

**Comment by bastidest2** [comment]
Die intellegente Einheitenkonvertierung würde ich einfach in eine User-Story auf GitHub schreiben, weil wir das nur machen wenn wir es schaffen. Aber ich denke das sollte keine Kernanforderung werden.

Deine Vorschläge hab ich eingepflegt.

**Comment by akramer123** [comment]
Subba, dann passt es für mich so
