### ISSUE TITLE
fix user stories

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#43]
-Beschreibung auf deutsch

**Comment by hmmst** [comment]
@bastidest2 @akramer123 könnt ihr nochmal durchschauen, ob alles passt..

**Comment by hmmst** [comment]
@bastidest2 @akramer123 bitte nochmal um review für die issues im Allgemeinen..

**Comment by akramer123** [comment]
@hmmst Bis auf meine Anmerkungen passen sie für mich!

**Comment by akramer123** [comment]
Wollen wir noch ein Label "Alexa skill functions" hinzufügen?

**Comment by bastidest2** [comment]
Für mich passt das jetzt

**Comment by akramer123** [comment]
Ja für mich auch
