### ISSUE TITLE
Intelligente Einheitenumwandlung

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#46]
Als Nutzer will ich, dass Einheiten möglichst anschaulich ausgegeben werden. Das heißt, dass 2000g als 2kg oder 0.015g als 15mg ausgeben werden.

Akzeptanzkriterien:
- Einheiten werden automatisch anhand der Mengenangabe in die nächstgrößere bzw -kleinere Einheit umgewandelt, sodass keine Zahlen > 1000 und < 0 ausgegeben werden müssen.

**Comment by bastidest2** [comment]
Überschreitet wie besprochen den Umfang, wird geschlossen.
