### ISSUE TITLE
Alexa setup

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#57]
Sprachauswertung, Zusammenspiel mit Backend, erster lauffähiger Skill

Dokumentation im Wiki

**Comment by bastidest2** [comment]
Aktueller Fortschritt: Lauffähiger dummy

![image](https://user-images.githubusercontent.com/43847839/48640157-163a6900-e9d6-11e8-8b43-8fd062982f1e.png)
