### ISSUE TITLE
Datenbank setup

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#58]
- [x] DynamoDB einrichten -> Wiki
- [x] Zugriff auf DynamoDB aus java
- [x] Dokumentation im Wiki -> #60

**Comment by hmmst** [comment]
aktueller Status:
https://github.com/sweIhm-ws2018-19/skillproject-fr-11/wiki/DynamoDB

@akramer123 @bastidest2 vllt habt ihr dazu noch eine Idee, was man ausprobieren bzw. was funktionieren könnte..

**Comment by akramer123** [comment]
@hmmst @bastidest2 
Was haltet ihr davon?
https://www.baeldung.com/spring-data-dynamodb

**Comment by bastidest2** [comment]
@hmmst @akramer123 Schaut euch mal an was ich bei #60 kommentiert habe. Das funktioniert super easy.

**Comment by akramer123** [comment]
@bastidest2 
Sieht für mich so aus, als ob man da nen generischen Service basteln kann wo man nur noch das zu speichernde Objekt übergeben kann oder? Dann find ichs gut.
Also sowas wie modelService.save(shoppingList);
modelService.get(shoppingList)

**Comment by bastidest2** [comment]
Genau, das kann man machen. Der muss nicht einmal generisch sein, ich würde das in ein Interface packen (wenn überhaupt). Es wird nämlich wenn man ShoppingList in Binary umwandelt, das komplette Objekt inclusive allen Membern gespeichert. Wir müssen ja nur ShoppingList und die Rezepte persistent speichern oder? Dann fehlt eigentlich nur noch dass wir das selbe noch zu den Rezepten hinzufügen.
