### ISSUE TITLE
Datenbank Dokumentation

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#60]
Datenbankschema anlegen und im Wiki Dokumentieren

Implementierung: #65 (#58)

**Comment by bastidest2** [comment]
@hmmst  Schau dir mal das hier an, vielleicht kannst du ja was verwerten (branch test/persistence): 

https://github.com/sweIhm-ws2018-19/skillproject-fr-11/blob/149995bb54e4cd9c2d8bf041412174ef878e5bb9/src/main/java/edu/hm/cs/seng/hypershop/handlers/AddIngredientIntentHandler.java#L53-L62

https://github.com/sweIhm-ws2018-19/skillproject-fr-11/blob/149995bb54e4cd9c2d8bf041412174ef878e5bb9/src/main/java/edu/hm/cs/seng/hypershop/model/ShoppingList.java#L46-L66

**Comment by hmmst** [comment]
sieht gut aus..:+1: probiere ich später aus..

dann wird das DB-Schema ja 1:1 auf das Model abgebildet..

**Comment by hmmst** [comment]
@bastidest2 @akramer123 fehlt noch etwas im [Wiki](https://github.com/sweIhm-ws2018-19/skillproject-fr-11/wiki/DynamoDB)?

und soll ich die "Ersten Versuch" löschen oder wollen wir die als Doku drinnen lassen?

**Comment by bastidest2** [comment]
Ich würde es als "Alternativansatz Datenbank" betiteln aber drinnen lassen

**Comment by hmmst** [comment]
@akramer123 dein Feedback?

**Comment by akramer123** [comment]
@hmmst 
Ich könnte nach dem Merge noch den ModelService mit seinen 2 Methoden erwähnen?
Sonst passt es, würde deinen Alternativansatz auch drinnen lassen.

**Comment by hmmst** [comment]
alles klar.. wäre super, wenn du den noch dazupacken würdest..:+1:

**Comment by akramer123** [comment]
Ist hinzugefügt.
