### ISSUE TITLE
UML Diagramme hinzufügen

### ISSUE THREAD

**Issue by hmmst** [sweIhm-ws2018-19/skillproject-fr-11#67]
Zu den User-Stories wäre es gut, wenn wir (falls möglich) Diagramme hinzufügen, um den Lösungsweg zu veranschaulichen.

**Comment by hmmst** [comment]
@bastidest2 könntest du das Anwendungsfalldiagramm aus Sprint 0 für den Sprint 1 kopieren und entsprechend den implementierten Anwendungsfällen anpassen?

**Comment by bastidest** [comment]
Was soll dann in das neue Diagramm? Nur die implementierten Sachen?

**Comment by hmmst** [comment]
genau, damit man sieht welche Use cases nach dem Sprint vorhanden sind..

**Comment by bastidest** [comment]
Und wohin soll das Diagramm dann? Ins wiki?

**Comment by hmmst** [comment]
ja hätte ich gesagt.. eine Wiki-Seite mit Sprint 1..

**Comment by bastidest** [comment]
https://github.com/sweIhm-ws2018-19/skillproject-fr-11/wiki/Sprint-1

Passt das so?

**Comment by hmmst** [comment]
@akramer123 passt das use case diagramm für dich auch?

**Comment by hmmst** [comment]
gäbe es sonst noch Diagramme, die man hinzufügen könnte?

**Comment by akramer123** [comment]
@hmmst 
Man könnte höchstens noch ein Sequenzdiagramm mit den verschiedenen Klassen beim AddIngredientHandler hinzufügen. Aber ist das nötig?

**Comment by hmmst** [comment]
ich habe den AddIngredientHandler noch nicht gesehen, aber wenn sich der Ablauf für ein Sequenzdiagramm eignet bzw. der Ablauf dadurch anschaulich beschrieben werden kann, warum nicht..:wink:

**Comment by bastidest2** [comment]
Wer soll das machen?

**Comment by akramer123** [comment]
@hmmst @bastidest 
https://github.com/sweIhm-ws2018-19/skillproject-fr-11/wiki/sprints

**Comment by akramer123** [comment]
@bastidest Aktualisiert

**Comment by bastidest2** [comment]
bis auf die fehlenden Doppelpunkte passt es haha

**Comment by akramer123** [comment]
@bastidest Unfassbar aber ich habe es geschafft.

**Comment by bastidest2** [comment]
unglaublich, er hat es geschafft. :1st_place_medal:  Kann von mir aus geschlossen werden @hmmst

**Comment by hmmst** [comment]
sieht gut aus.. :+1: dann schließe ich es mal wieder.. :joy:
